//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnipForMammal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int updateAuthTokenInterval {
            get {
                return ((int)(this["updateAuthTokenInterval"]));
            }
            set {
                this["updateAuthTokenInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int updateSpotifyTrackInfoInterval {
            get {
                return ((int)(this["updateSpotifyTrackInfoInterval"]));
            }
            set {
                this["updateSpotifyTrackInfoInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoCloseAuthWindow {
            get {
                return ((bool)(this["autoCloseAuthWindow"]));
            }
            set {
                this["autoCloseAuthWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int updateCurrentTrackPlayingInterval {
            get {
                return ((int)(this["updateCurrentTrackPlayingInterval"]));
            }
            set {
                this["updateCurrentTrackPlayingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"$song\" - $artist")]
        public string outputFormat {
            get {
                return ((string)(this["outputFormat"]));
            }
            set {
                this["outputFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int defaultUpdateAuthTokenInterval {
            get {
                return ((int)(this["defaultUpdateAuthTokenInterval"]));
            }
            set {
                this["defaultUpdateAuthTokenInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int defaultUpdateSpotifyTrackInfoInterval {
            get {
                return ((int)(this["defaultUpdateSpotifyTrackInfoInterval"]));
            }
            set {
                this["defaultUpdateSpotifyTrackInfoInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool defaultAutoCloseAuthWindow {
            get {
                return ((bool)(this["defaultAutoCloseAuthWindow"]));
            }
            set {
                this["defaultAutoCloseAuthWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int defaultUpdateCurrentTrackPlayingInterval {
            get {
                return ((int)(this["defaultUpdateCurrentTrackPlayingInterval"]));
            }
            set {
                this["defaultUpdateCurrentTrackPlayingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"$song\" - $artist")]
        public string defaultOutputFormat {
            get {
                return ((string)(this["defaultOutputFormat"]));
            }
            set {
                this["defaultOutputFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chrome")]
        public string defaultBrowser {
            get {
                return ((string)(this["defaultBrowser"]));
            }
            set {
                this["defaultBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chrome")]
        public string browser {
            get {
                return ((string)(this["browser"]));
            }
            set {
                this["browser"] = value;
            }
        }
    }
}
